logging.level.org.springframework.security: DEBUG

#security:
#    oauth2:
#      resource:
#        user-info-uri: http://localhost:9999/uaa/user

server:
  port: 9000
  address: 127.0.0.1

spring:
  redis:
    host: localhost
    port: 6379
    database: 0
  session:
    store-type: redis


